# RT001_Introdução à Teoria da Informação Codificação de Fonte e Canal

## Libraries

In [255]:
import pandas as pd
import numpy as np
import math
from itertools import product, combinations

# import laguide as lag

### Sinal e probabilidades

In [3]:
# S0, S1 e S2 -> A, I e W
s = ['000', '100', '111']
p = [0.5, 0.3, 0.2]

### Decodificador

In [4]:
math.log2(2)

1.0

### huffman algorithm python

In [8]:
# https://www.programiz.com/dsa/huffman-coding

### Exercicio 1

In [9]:
# S0, S1, S2, S3, S4
prob = [0.1, 0.25, 0.40, 0.20, 0.05]

In [10]:
def entropiaFonte(prob):
    return sum([prob[indice] * math.log2(1.0/prob[indice]) for indice in range(len(prob))])

In [11]:
H = entropiaFonte(prob)
print (H)

2.041446071165522


In [12]:
# S0, S1, S2, S3, S4
palavrasCodigos = ['0010', '01', '1', '000', '0011']

In [13]:
def comprimentoMedio(listaPalavras, prob):
    tamanhoPalavra = [len(palavra) for palavra in listaPalavras]
    return sum([tamanhoPalavra[indice] * prob[indice] for indice in range(len(tamanhoPalavra))])

In [14]:
L = comprimentoMedio(palavrasCodigos, prob)
print(L)

2.1


In [15]:
Eficiencia = H/L
print(Eficiencia)

0.9721171767454866


In [16]:
print(f"A eficiencia desta bagaça é de {Eficiencia*100:.4f} %")

A eficiencia desta bagaça é de 97.2117 %


## Subespaço vetorial

https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/Linear_Independence.html

Preciso entender isso ainda...

In [17]:
S = [[0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [1, 1, 0, 0, 1],
    [0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1],
    [1, 1, 1, 1, 0],
    [1, 0, 1, 0, 1]]

In [18]:
S_augmented = np.array(S)
S_augmented

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

In [19]:
A_augmented = np.array([[2,1,0],[1,-6,0]])
# print(lag.FullRowReduction(A_augmented))

np.linalg.qr(A_augmented, 'complete')

(array([[-0.89442719, -0.4472136 ],
        [-0.4472136 ,  0.89442719]]),
 array([[-2.23606798,  1.78885438,  0.        ],
        [ 0.        , -5.81377674,  0.        ]]))

In [20]:
ref, pivots = np.linalg.qr(S_augmented, 'complete')

## Matrix Geradora

### Array de mensagens 

De 000 a 111

In [256]:
# Generate all binary combinations
combinationsOfMessages = product([0, 1], repeat=3)

# Convert each combination to a NumPy array
messages = [np.array(combination) for combination in combinationsOfMessages]
messages

[array([0, 0, 0]),
 array([0, 0, 1]),
 array([0, 1, 0]),
 array([0, 1, 1]),
 array([1, 0, 0]),
 array([1, 0, 1]),
 array([1, 1, 0]),
 array([1, 1, 1])]

### Matriz Geradora Exemplo 2.8 slide 61

Utilza os vetores da base

In [257]:
G = np.array([
    [0, 1, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [0, 1, 1, 0, 0]
])

# message = np.array([1, 0, 0])

In [293]:
def gerarVetoresCodigo(M_G, M_Messages):
    codes = []
    for message in M_Messages:
        mult = (message * M_G.T).T
        code = np.bitwise_xor.reduce(mult, axis=0)
        dict_code = {
            "message": message,
            "code": code
        }
        codes.append(dict_code)
    return pd.DataFrame(codes)

In [291]:
vetoresCodigos = gerarVetoresCodigo(G, messages)
vetoresCodigos

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [0, 1, 1, 0, 0]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [1, 1, 1, 1, 0]
4  [1, 0, 0]  [0, 1, 0, 1, 1]
5  [1, 0, 1]  [0, 0, 1, 1, 1]
6  [1, 1, 0]  [1, 1, 0, 0, 1]
7  [1, 1, 1]  [1, 0, 1, 0, 1]

### Matriz geradora: Exemplo 2.9

Separar o código da paridade

In [259]:
k = np.size(G, axis=0)
n = np.size(G, axis=1)
I = np.identity(3, dtype=int) # matriz identidade

print(f"Matriz geradora:\n{G}")
print(f"\nk={k} linhas por n={n} colunas\n")
print(f"Matriz identidade:\n{I}")

Matriz geradora:
[[0 1 0 1 1]
 [1 0 0 1 0]
 [0 1 1 0 0]]

k=3 linhas por n=5 colunas

Matriz identidade:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Gerando combinações

g0 = [0, 1, 0, 1, 1]</br>
g1 = [1, 0, 0, 1, 0]</br>
g2 = [0, 1, 1, 0, 0]</br>

#### Possibilidades: 
* g0 **XOR** g1        = [1, 1, 0, 0, 1]
* g0 **XOR** g2        = [0, 0, 1, 1, 1]
* g1 **XOR** g2        = [1, 1, 1, 1, 0]
* g0 **XOR** g1 XOR g2 = [1, 0, 1, 0, 1]

In [266]:
def generateCombinations(matrix):
    rows_count = matrix.shape[0] # k linhas
    combination_list = []
    # Generate all combinations of rows
    for r in range(1, rows_count + 1):
        combination_list.extend(combinations(range(rows_count), r))

    # Calculate XOR for each combination
    row_xor = [np.bitwise_xor.reduce(matrix[list(comb)], axis=0) for comb in combination_list]

    return np.array(row_xor)

In [269]:
combs = generateCombinations(G)
combs

array([[0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

A matriz paridade tem dimensões k X n-2 ou 3x2

### Matriz sistemática e de Paridade

In [302]:
def generateSistematicGandParity(M_Identity, M_Combinations, n):
    G_systematic_List = []
    parity_matrix_List = []
    for row_i in M_Identity:
        for comb in M_Combinations:
            parity = comb[:n-2-1]
            code_from_G = comb[n-2-1:]

            if np.array_equal(row_i, code_from_G):
                g_systematic = np.concatenate((parity, row_i))
                
                G_systematic_List.append(g_systematic)
                parity_matrix_List.append(parity)
    
    return np.array(G_systematic_List), np.array(parity_matrix_List)

In [303]:
n = combs[0].shape[0]
G_systematic, P_matrix = generateSistematicGandParity(I, combs, n)
print(G_systematic, '\n')
print(P_matrix)

[[0 1 1 0 0]
 [1 0 0 1 0]
 [1 1 0 0 1]] 

[[0 1]
 [1 0]
 [1 1]]


### Gerando novos codigos

In [294]:
vetoresCodigos2 = gerarVetoresCodigo(G_systematic, messages)
vetoresCodigos2

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [1, 1, 0, 0, 1]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [0, 1, 0, 1, 1]
4  [1, 0, 0]  [0, 1, 1, 0, 0]
5  [1, 0, 1]  [1, 0, 1, 0, 1]
6  [1, 1, 0]  [1, 1, 1, 1, 0]
7  [1, 1, 1]  [0, 0, 1, 1, 1]

## Matrix Verificadora de Paridade: Exemplo 2.10

 H, e tem dimensões (n – k) x n

In [318]:
G_systematic

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1]])

In [457]:
p

array([1, 0])

#### Nova identidade

In [319]:
I2 = np.identity(n-k, dtype=int) # matriz identidade
I2.T

array([[1, 0],
       [0, 1]])

#### A - Gerando matriz verificadora de paridade H

In [339]:
def gerarMatrizVerificadoraParidade(I, P):
    h_list = []
    for index in range(P.T.shape[0]):
        h = np.concatenate((I[index], P.T[index]))
        h_list.append(h)
    
    return np.array(h_list)

In [340]:
H = gerarMatrizVerificadoraParidade(I2, P_matrix)
H

array([[1, 0, 0, 1, 1],
       [0, 1, 1, 0, 1]])

#### B - Verificar a condição de ortogonalidade para o vetor código correspondente ao vetor mensagem m = 101

c = m * G

In [345]:
G_systematic

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1]])

#### Vetor código

In [365]:
m = [1, 0, 1]
vetorCodigo_m = gerarVetoresCodigo(G_systematic, np.array([m]))['code'].iloc[0]
vetorCodigo_m

array([1, 0, 1, 0, 1])

#### Verificar ortogonalidade

c * H_transposto

In [448]:
vetorCodigo_m, H.T

(array([1, 0, 1, 0, 1]),
 array([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 1]]))

In [466]:
def verificarOrtogonalidade(vetor_codigo, matrix_H):
    
    arr1 = vetor_codigo
    arr2 = matrix_H.T

    result = np.zeros(arr2.shape[1], dtype=int)  # Initialize result array with zeros

    for i in range(len(arr1)):
        for j in range(arr2.shape[1]):
            result[j] ^= int(arr1[i]) * int(arr2[i, j])

    return np.bitwise_xor.reduce(result)

In [467]:
verificarOrtogonalidade(vetorCodigo_m, H)

0

In [470]:
verificarOrtogonalidade(np.array([1, 1, 1, 0, 1]), H)

1

## Distância mínima de um código de bloco linear

#### Matriz geradora exemplo 2.11
Matrix geradora código (6, 3) = (n, k)

In [474]:
G = np.array([
    [1, 0, 1, 1, 0, 0],
    [1, 1, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 1]
])

G

array([[1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1]])

#### Mensagens

In [477]:
messages

[array([0, 0, 0]),
 array([0, 0, 1]),
 array([0, 1, 0]),
 array([0, 1, 1]),
 array([1, 0, 0]),
 array([1, 0, 1]),
 array([1, 1, 0]),
 array([1, 1, 1])]

#### Vetores codigo

In [516]:
df_distancia = gerarVetoresCodigo(G, messages)
df_distancia['weight'] = df_distancia['code'].apply(lambda x: np.count_nonzero(x))

weight_list = df_distancia.weight.sort_values().to_list()
dmin = min([x for x in weight_list if x != 0], default=0)
dmin

display(df_distancia)
print(f"Distância mínima = {dmin}")

message                code  weight
0  [0, 0, 0]  [0, 0, 0, 0, 0, 0]       0
1  [0, 0, 1]  [0, 1, 1, 0, 0, 1]       3
2  [0, 1, 0]  [1, 1, 0, 0, 1, 0]       3
3  [0, 1, 1]  [1, 0, 1, 0, 1, 1]       4
4  [1, 0, 0]  [1, 0, 1, 1, 0, 0]       3
5  [1, 0, 1]  [1, 1, 0, 1, 0, 1]       4
6  [1, 1, 0]  [0, 1, 1, 1, 1, 0]       4
7  [1, 1, 1]  [0, 0, 0, 1, 1, 1]       3

Distância mínima = 3


### Exemplo 2.11 slide 75

In [502]:
# Matriz geradora já sistematizada
G

array([[1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1]])

In [503]:
# Matrix de paridade
P_matrix = G[:, :3]
P_matrix

array([[1, 0, 1],
       [1, 1, 0],
       [0, 1, 1]])

In [510]:
# Matriz identidade
n = G.shape[1]
k = G.shape[0]
I3 = np.identity(n-k, dtype=int) # matriz identidade
I3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [511]:
H = gerarMatrizVerificadoraParidade(I3, P_matrix)
H

array([[1, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1]])

In [517]:
print(f"A notação usada com distância mínima deve ser (n, k, dmin) = ({n}, {k}, {dmin})")

A notação usada com distância mínima deve ser (n, k, dmin) = (6, 3, 3)


### Capacidade de correção e de detecção de erros e um código de bloco linear

In [528]:
t = (dmin -1) / 2
e = dmin - 1
print(f"O código ({n}, {k}, {dmin}) é capaz de corrigir todos os padrões de {t} bit errado.\nSe houver mais de {t} erros o código não irá corrigir.")
print(f"A capacidade mínima de detectar é de {e} erros detectados.")

O código (6, 3, 3) é capaz de corrigir todos os padrões de 1.0 bit errado.
Se houver mais de 1.0 erros o código não irá corrigir.
A capacidade mínima de detectar é de 2 erros detectados.


## Síndrome de Erro

#### Matriz geradora em forma sistemática

In [553]:
G

array([[1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1]])

#### a)Determinar a capacidade de correção de erros do código.

In [554]:
print(f"O código ({n}, {k}, {dmin}) é capaz de corrigir todos os padrões de {t} bit errado.\nSe houver mais de {t} erros o código não irá corrigir.")
print(f"A capacidade mínima de detectar é de {e} erros detectados.")

O código (6, 3, 3) é capaz de corrigir todos os padrões de 1.0 bit errado.
Se houver mais de 1.0 erros o código não irá corrigir.
A capacidade mínima de detectar é de 2 erros detectados.


#### b)Listar todos os padrões de erros corrigíveis dentro da capacidade de correção de erros do código.

In [569]:
# hardcoded mas por hora funciona
def listarErros(n):
    matrix = np.eye(n, dtype=int)
    return np.flip(matrix, axis=1)

In [573]:
e = listarErros(n)
e

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

#### c)Listar todas as síndromes de erros associadas aos padrões de erros corrigíveis dentro da capacidade de correção de erros do código.

In [572]:
H.T

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 1],
       [1, 1, 0],
       [0, 1, 1]])

In [575]:
S = gerarVetoresCodigo(H.T, e)
S

message       code
0  [0, 0, 0, 0, 0, 1]  [0, 1, 1]
1  [0, 0, 0, 0, 1, 0]  [1, 1, 0]
2  [0, 0, 0, 1, 0, 0]  [1, 0, 1]
3  [0, 0, 1, 0, 0, 0]  [0, 0, 1]
4  [0, 1, 0, 0, 0, 0]  [0, 1, 0]
5  [1, 0, 0, 0, 0, 0]  [1, 0, 0]

In [576]:
# Padrões de erros corrigíveis e suas respectivas síndromes para o código de bloco linear (6, 3, 3), dados pela matriz G

### Correção de erros pela Síndrome - Exemplo 2.13

In [577]:
# Faltam duas gravações

## PLAYGROUND E ASSUNTOS BIZARROS

In [292]:
codes = []
for message in messages:
    mult = (message * G.T).T
    code = np.bitwise_xor.reduce(mult, axis=0)
#     decoded = np.roll(code, 1)[:3]
#     isCorrectDecoded = (np.array_equal(np.array(message), np.array(decoded)))
    dict_code = {
        "message": message,
        "code": code,
#         "isDecoded": isCorrectDecoded
    }
    codes.append(dict_code)
        
df = pd.DataFrame(codes)
df

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [0, 1, 1, 0, 0]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [1, 1, 1, 1, 0]
4  [1, 0, 0]  [0, 1, 0, 1, 1]
5  [1, 0, 1]  [0, 0, 1, 1, 1]
6  [1, 1, 0]  [1, 1, 0, 0, 1]
7  [1, 1, 1]  [1, 0, 1, 0, 1]

In [409]:
arr1 = np.array([1, 0, 1, 0, 1])
arr2 = np.array([[1, 0],
                 [0, 1],
                 [0, 1],
                 [1, 0],
                 [1, 1]])

result = np.zeros(arr2.shape[1], dtype=int)  # Initialize result array with zeros

for i in range(len(arr1)):
    for j in range(arr2.shape[1]):
        result[j] ^= int(arr1[i]) * int(arr2[i, j])

print(result)

[0 0]


In [562]:
# Define the size of the desired matrix
size = 6

# Create a diagonal matrix with ones along the main diagonal
matrix = np.eye(size, dtype=int)

# Reverse the matrix to get the desired pattern
result = np.flip(matrix, axis=1)

print(result)

[[0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]]


In [563]:
# Create a matrix of zeros
result = np.zeros((size, size), dtype=int)

# Set the diagonal elements to 1
for i in range(size):
    result[i, size-i-1] = 1

print(result)

[[0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]]
