# RT001_Introdução à Teoria da Informação Codificação de Fonte e Canal

## Libraries

In [255]:
import pandas as pd
import numpy as np
import math
from itertools import product, combinations

# import laguide as lag

### Sinal e probabilidades

In [3]:
# S0, S1 e S2 -> A, I e W
s = ['000', '100', '111']
p = [0.5, 0.3, 0.2]

### Decodificador

In [4]:
math.log2(2)

1.0

### huffman algorithm python

In [8]:
# https://www.programiz.com/dsa/huffman-coding

### Exercicio 1

In [9]:
# S0, S1, S2, S3, S4
prob = [0.1, 0.25, 0.40, 0.20, 0.05]

In [10]:
def entropiaFonte(prob):
    return sum([prob[indice] * math.log2(1.0/prob[indice]) for indice in range(len(prob))])

In [11]:
H = entropiaFonte(prob)
print (H)

2.041446071165522


In [12]:
# S0, S1, S2, S3, S4
palavrasCodigos = ['0010', '01', '1', '000', '0011']

In [13]:
def comprimentoMedio(listaPalavras, prob):
    tamanhoPalavra = [len(palavra) for palavra in listaPalavras]
    return sum([tamanhoPalavra[indice] * prob[indice] for indice in range(len(tamanhoPalavra))])

In [14]:
L = comprimentoMedio(palavrasCodigos, prob)
print(L)

2.1


In [15]:
Eficiencia = H/L
print(Eficiencia)

0.9721171767454866


In [16]:
print(f"A eficiencia desta bagaça é de {Eficiencia*100:.4f} %")

A eficiencia desta bagaça é de 97.2117 %


## Subespaço vetorial

https://bvanderlei.github.io/jupyter-guide-to-linear-algebra/Linear_Independence.html

Preciso entender isso ainda...

In [17]:
S = [[0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [1, 1, 0, 0, 1],
    [0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1],
    [1, 1, 1, 1, 0],
    [1, 0, 1, 0, 1]]

In [18]:
S_augmented = np.array(S)
S_augmented

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

In [19]:
A_augmented = np.array([[2,1,0],[1,-6,0]])
# print(lag.FullRowReduction(A_augmented))

np.linalg.qr(A_augmented, 'complete')

(array([[-0.89442719, -0.4472136 ],
        [-0.4472136 ,  0.89442719]]),
 array([[-2.23606798,  1.78885438,  0.        ],
        [ 0.        , -5.81377674,  0.        ]]))

In [20]:
ref, pivots = np.linalg.qr(S_augmented, 'complete')

## Matrix Geradora

### Array de mensagens 

De 000 a 111

In [256]:
# Generate all binary combinations
combinationsOfMessages = product([0, 1], repeat=3)

# Convert each combination to a NumPy array
messages = [np.array(combination) for combination in combinationsOfMessages]
messages

[array([0, 0, 0]),
 array([0, 0, 1]),
 array([0, 1, 0]),
 array([0, 1, 1]),
 array([1, 0, 0]),
 array([1, 0, 1]),
 array([1, 1, 0]),
 array([1, 1, 1])]

### Matriz Geradora Exemplo 2.8 slide 61

Utilza os vetores da base

In [257]:
G = np.array([
    [0, 1, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [0, 1, 1, 0, 0]
])

# message = np.array([1, 0, 0])

In [293]:
def gerarVetoresCodigo(M_G, M_Messages):
    codes = []
    for message in M_Messages:
        mult = (message * M_G.T).T
        code = np.bitwise_xor.reduce(mult, axis=0)
        dict_code = {
            "message": message,
            "code": code
        }
        codes.append(dict_code)
    return pd.DataFrame(codes)

In [291]:
vetoresCodigos = gerarVetoresCodigo(G, messages)
vetoresCodigos

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [0, 1, 1, 0, 0]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [1, 1, 1, 1, 0]
4  [1, 0, 0]  [0, 1, 0, 1, 1]
5  [1, 0, 1]  [0, 0, 1, 1, 1]
6  [1, 1, 0]  [1, 1, 0, 0, 1]
7  [1, 1, 1]  [1, 0, 1, 0, 1]

### Matriz geradora: Exemplo 2.9

Separar o código da paridade

In [259]:
k = np.size(G, axis=0)
n = np.size(G, axis=1)
I = np.identity(3, dtype=int) # matriz identidade

print(f"Matriz geradora:\n{G}")
print(f"\nk={k} linhas por n={n} colunas\n")
print(f"Matriz identidade:\n{I}")

Matriz geradora:
[[0 1 0 1 1]
 [1 0 0 1 0]
 [0 1 1 0 0]]

k=3 linhas por n=5 colunas

Matriz identidade:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Gerando combinações

g0 = [0, 1, 0, 1, 1]</br>
g1 = [1, 0, 0, 1, 0]</br>
g2 = [0, 1, 1, 0, 0]</br>

#### Possibilidades: 
* g0 **XOR** g1        = [1, 1, 0, 0, 1]
* g0 **XOR** g2        = [0, 0, 1, 1, 1]
* g1 **XOR** g2        = [1, 1, 1, 1, 0]
* g0 **XOR** g1 XOR g2 = [1, 0, 1, 0, 1]

In [266]:
def generateCombinations(matrix):
    rows_count = matrix.shape[0] # k linhas
    combination_list = []
    # Generate all combinations of rows
    for r in range(1, rows_count + 1):
        combination_list.extend(combinations(range(rows_count), r))

    # Calculate XOR for each combination
    row_xor = [np.bitwise_xor.reduce(matrix[list(comb)], axis=0) for comb in combination_list]

    return np.array(row_xor)

In [269]:
combs = generateCombinations(G)
combs

array([[0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1]])

A matriz paridade tem dimensões k X n-2 ou 3x2

### Matriz sistemática

In [278]:
def generateSistematicG(M_Identity, M_Combinations, n):
    G_systematic_List = []
    for row_i in M_Identity:
        for comb in M_Combinations:
            parity = comb[:n-2-1]
            code_from_G = comb[n-2-1:]

            if np.array_equal(row_i, code_from_G):
                g_systematic = np.concatenate((parity, row_i))
                G_systematic_List.append(g_systematic)
    
    return np.array(G_systematic_List)

In [280]:
n = combs[0].shape[0]
G_systematic = generateSistematicG(I, combs, n)
G_systematic

array([[0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1]])

### Gerando novos codigos

In [294]:
vetoresCodigos2 = gerarVetoresCodigo(G_systematic, messages)
vetoresCodigos2

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [1, 1, 0, 0, 1]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [0, 1, 0, 1, 1]
4  [1, 0, 0]  [0, 1, 1, 0, 0]
5  [1, 0, 1]  [1, 0, 1, 0, 1]
6  [1, 1, 0]  [1, 1, 1, 1, 0]
7  [1, 1, 1]  [0, 0, 1, 1, 1]

## PLAYGROUND E ASSUNTOS BIZARROS

In [292]:
codes = []
for message in messages:
    mult = (message * G.T).T
    code = np.bitwise_xor.reduce(mult, axis=0)
#     decoded = np.roll(code, 1)[:3]
#     isCorrectDecoded = (np.array_equal(np.array(message), np.array(decoded)))
    dict_code = {
        "message": message,
        "code": code,
#         "isDecoded": isCorrectDecoded
    }
    codes.append(dict_code)
        
df = pd.DataFrame(codes)
df

message             code
0  [0, 0, 0]  [0, 0, 0, 0, 0]
1  [0, 0, 1]  [0, 1, 1, 0, 0]
2  [0, 1, 0]  [1, 0, 0, 1, 0]
3  [0, 1, 1]  [1, 1, 1, 1, 0]
4  [1, 0, 0]  [0, 1, 0, 1, 1]
5  [1, 0, 1]  [0, 0, 1, 1, 1]
6  [1, 1, 0]  [1, 1, 0, 0, 1]
7  [1, 1, 1]  [1, 0, 1, 0, 1]